### ISSUE TITLE
When will you deem it necessary to implement quantum resistant cryptography.

### ISSUE THREAD

**Issue by Destroyinator69420** [Tribler/py-ipv8#1013] opened 2021-07-05 01:49 UTC
I worry about the long term viability of AES to withstand quantum computers. Shor's Algorithm can half the difficulty of cracking the private key for AES, but it can crack 2048 bit RSA keys and most ECC cryptography. When will you implement quantum resistant cryptography? The OpenQuantumSafe project implements these algorithms in C, but I am not aware of a python binding, nor has NIST declared a winner of the public contests for quantum resistant cryptography.

**Comment by qstokkink** [comment] 2021-07-06 07:15
To an extent, IPv8 is already ready to fully switch to quantum-secure mechanisms and protocols. Our architecture is modular enough to make such a switch. Some of IPv8 is even already quantum-secure.

The problem is that we do not know what we are defending against. Many of the quantum attacks and defenses are still theoretical. In many ways "How will you defend against quantum attacks?" is still analogous to "How will you defend earth against an alien attack?". _We think_ we have ways to protect ourselves, but _we won't know for sure_ exactly what works and what doesn't until it actually happens.

With that in mind, to answer your question: we deem it necessary to implement quantum resistant cryptography once (1) real attacks are shown to be effective and (2) we know this "quantum resistant" cryptography actually works to deter them.

**Comment by qstokkink** [comment] 2021-07-13 08:27
After a week of silence I assume this question has been sufficiently answered. Closing this isue.

**Closed by qstokkink** 2021-07-13 08:27 UTC
Labels: question
