### ISSUE TITLE
Function parameters written to before being read

### ISSUE THREAD

**Issue by Solomon1732** [Tribler/py-ipv8#640] opened 2019-12-25 09:12 UTC
A number of function parameters are written to, before they are read, meaning the original value they had is written over. Looks like they were meant to be used but for some reason aren't.

Instead of writing a long post I created this paste bin. Hope it helps.
https://gist.github.com/Solomon1732/e6470d463c257dca18f03cbd3467162a

**Comment by Solomon1732** [comment] 2019-12-25 09:13
An example of what I'm talking about is [this](https://github.com/Tribler/py-ipv8/blob/master/ipv8/messaging/anonymization/community.py#L645)
```python
# extra_bytes declared here
def create_introduction_request(self, socket_address, extra_bytes=b''):
    extra_payload = ExtraIntroductionPayload(self.settings.peer_flags)
    # But is first used here
    extra_bytes = self.serializer.pack_multiple(extra_payload.to_pack_list())[0]
    return super(TunnelCommunity, self).create_introduction_request(socket_address, extra_bytes)
```

**Comment by Solomon1732** [comment] 2019-12-25 09:22
I took the list from here:
https://sonarcloud.io/project/issues?id=org.sonarqube%3Atribler&pullRequest=655da829a18c784673661c25df1f240658f416cc&resolved=false&types=BUG)

It was a test for PR Tribler/tribler#5012 . The major issue mentioned in the link I provided was already fixed with PR Tribler/tribler#5017

**Comment by devos50** [comment] 2019-12-25 10:26
I think we should disable the scan of the IPv8 directory in Sonarqube since it's a submodule. The same goes for AnyDex.

We could add a separate Sonarqube PR checker to PRs opened on this repo. However, that would require maintainance of one more Jenkins job. @qstokkink what do you think?

**Comment by qstokkink** [comment] 2019-12-25 12:49
These are confirmed false positives for override functions. Nothing to worry about, I'll close this issue.

> I think we should disable the scan of the IPv8 directory in Sonarqube when a PR is opened on Tribler since it's a submodule.

Agreed.

> We could add a separate Sonarqube PR checker to PRs opened on this repo.

@xoriole already made this.

**Closed by qstokkink** 2019-12-25 12:49 UTC
Labels: enhancement
