### ISSUE TITLE
DHTCommunity "'NoneType' object has no attribute 'number'"

### ISSUE THREAD

**Issue by ichorid** [Tribler/py-ipv8#800] opened 2020-07-03 12:06 UTC
**Tribler 7.5.1, Windows 10**

from Reporter

```python


Traceback (most recent call last):
File "src\tribler-gui\tribler_gui\event_request_manager.py", line 112, in on_read_data
RuntimeError: 'NoneType' object has no attribute 'number'
--LONG TEXT--
Traceback (most recent call last):
File "ipv8\dht\community.py", line 389, in _contact_node
File "ipv8\dht\community.py", line 383, in _send_find_request
AttributeError: 'NoneType' object has no attribute 'number'

--CONTEXT--
{'message': 'Task exception was never retrieved', 'exception': AttributeError("'NoneType' object has no attribute 'number'"), 'future': <Task finished coro=<DHTCommunity._contact_node() done, defined at ipv8\dht\community.py:386> exception=AttributeError("'NoneType' object has no attribute 'number'")>}

```

**Comment by qstokkink** [comment] 2020-07-03 12:09
@egbertbouman you fixed this already right?

**Comment by qstokkink** [comment] 2020-07-03 12:10
Nvm found it. Duplicate of #770, closing.

**Comment by qstokkink** [comment] 2020-07-03 12:11
I believe the pointer was also updated on the `release-7.5` branch in Tribler already.

**Closed by qstokkink** 2020-07-03 12:10 UTC
Labels: bug
