### ISSUE TITLE
test_build_proofs failing

### ISSUE THREAD

**Issue by devos50** [Tribler/py-ipv8#641] opened 2019-12-25 11:13 UTC
Observed on Linux (https://jenkins-ci.tribler.org/job/ipv8/job/test_ipv8_PR_unittests_linux/1497/console):

```
test_task_with_exception_ignore (ipv8.test.test_taskmanager.TestTaskManager) ... ERROR:TaskManager:Task resulted in error: division by zero
ok

======================================================================
FAIL: test_build_proofs (ipv8.test.attestation.wallet.irmaexact.test_builder.TestBuilder)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jenkins/.local/lib/python3.7/site-packages/asynctest/case.py", line 297, in run
    self._run_test_method(testMethod)
  File "/home/jenkins/.local/lib/python3.7/site-packages/asynctest/case.py", line 352, in _run_test_method
    result = method()
  File "/home/jenkins/ci/workspace/ipv8/test_ipv8_PR_unittests_linux/ipv8/test/attestation/wallet/irmaexact/test_builder.py", line 85, in test_build_proofs
    self.assertFalse(proof.Verify(self.testPubK, sig, 10, nonce))
AssertionError: True is not false
```

**Comment by qstokkink** [comment] 2019-12-25 12:46
This is a source port from the IRMA project: if we "fix" it, we break the compatibility.

I was thinking of skipping these tests, but this does not happen that often.

If this starts occurring more often I'll disable the tests after all. For now, won't fix.

**Comment by qstokkink** [comment] 2019-12-25 12:56
After a second look, this appears to happen after the PR tests have been set to run on Python 3 for some reason (who did this?). Probably a Python 3 thing, this warrants further investigation.

If it turns out to not be Python 3, but the IRMA protocol this will go back to `wont address`.

**Comment by qstokkink** [comment] 2019-12-25 13:13
OP also seems to be Python 3. I'll run some stress tests.

**Comment by qstokkink** [comment] 2019-12-25 14:18
Not just Python 3, also confirmed with `unittest` test runner on Python 2.7:

```
======================================================================
FAIL: test_build_proofs (ipv8.test.attestation.wallet.irmaexact.test_builder.TestBuilder)
test_build_proofs
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 151, in maybeDeferred
    result = f(*args, **kw)
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/internet/utils.py", line 201, in runWithWarningsSuppressed
    reraise(exc_info[1], exc_info[2])
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/internet/utils.py", line 197, in runWithWarningsSuppressed
    result = f(*a, **kw)
  File "ipv8/test/attestation/wallet/irmaexact/test_builder.py", line 86, in test_build_proofs
    self.assertFalse(proof.Verify(self.testPubK, sig, context, 10))
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/trial/_synctest.py", line 384, in assertFalse
    super(_Assertions, self).assertFalse(condition, msg)
  File "/usr/lib/python2.7/unittest/case.py", line 416, in assertFalse
    raise self.failureException(msg)
FailTest: True is not false

----------------------------------------------------------------------
```

**Comment by qstokkink** [comment] 2019-12-25 14:20
Also fails with `nosetests` for Python 2.7:

```
======================================================================
FAIL: test_build_proofs
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 151, in maybeDeferred
    result = f(*args, **kw)
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/internet/utils.py", line 201, in runWithWarningsSuppressed
    reraise(exc_info[1], exc_info[2])
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/internet/utils.py", line 197, in runWithWarningsSuppressed
    result = f(*a, **kw)
  File "/home/quinten/Documents/py-ipv8/ipv8/test/attestation/wallet/irmaexact/test_builder.py", line 86, in test_build_proofs
    self.assertFalse(proof.Verify(self.testPubK, sig, context, 10))
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/trial/_synctest.py", line 384, in assertFalse
    super(_Assertions, self).assertFalse(condition, msg)
  File "/usr/lib/python2.7/unittest/case.py", line 416, in assertFalse
    raise self.failureException(msg)
FailTest: True is not false

----------------------------------------------------------------------
```

**Comment by qstokkink** [comment] 2019-12-25 14:26
🤦‍♂ This test generates a random integer and then checks if this random integer is not some other fixed value. HOWEVER, there is nothing to prevent this random value from being equal to the fixed value. This test is failing when the generated nonce is equal to `10`.

https://github.com/Tribler/py-ipv8/blob/59cdb4246c28fd4f8a262a57a70a8dd88ab8f0ee/ipv8/test/attestation/wallet/irmaexact/test_builder.py#L78

https://github.com/Tribler/py-ipv8/blob/59cdb4246c28fd4f8a262a57a70a8dd88ab8f0ee/ipv8/test/attestation/wallet/irmaexact/test_builder.py#L85-L86

**Closed** 2019-12-25 18:41 UTC
Labels: bug
