### ISSUE TITLE
"UserWarning: Multiple schemas resolved" when starting Tribler

### ISSUE THREAD

**Issue by devos50** [Tribler/py-ipv8#1062] opened 2021-10-08 13:37 UTC
When starting Tribler, I noticed two warnings in the log:

```
/usr/local/lib/python3.9/site-packages/apispec/ext/marshmallow/common.py:139: UserWarning: Multiple schemas resolved to the name GetChannelContentsResponse. The name has been modified. Either manually add each of the schemas with a different name or provide a custom schema_name_resolver.
  warnings.warn(
/usr/local/lib/python3.9/site-packages/apispec/ext/marshmallow/common.py:139: UserWarning: Multiple schemas resolved to the name SpeedTestRequest. The name has been modified. Either manually add each of the schemas with a different name or provide a custom schema_name_resolver.
  warnings.warn(
```

It seems that there are multiple Marshmallow schemes declared with the same name, which triggers this warning.

**Comment by ichorid** [comment] 2021-11-23 18:42
The relevant lines have been already removed in Tribler. Only the duplicated SpeedTest thing persists in IPv8

**Comment by qstokkink** [comment] 2021-11-23 19:03
Duplicate of #1053

**Closed by qstokkink** 2021-11-23 19:03 UTC
